#!/usr/bin/zsh

# para backupear un dir que está en $external_drive/ me paro dentro del dir y hago backup_ext %d (si estoy en vifm)
#rsync -av $1 $sd/

# para backupear defaults
rsync -av $HOME/wiki $sd/
