#!/usr/bin/zsh
#mkdir usb
go-mtpfs external_drives/android &
st -e vifm external_drives/android
#export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1003/bus
#nautilus
#pkill nautilus
#st -e vifm /run/user/1000/gvfs/mtp:host=Xiaomi_TRINKET-IDP__SN%3A95D39118_1015d472
