#!/usr/bin/zsh

#start=$(echo "" | dmenu -p "en qué dir empezar:")

#if [[ -n "$start" && -d "$start" ]]; then
  #st -e zsh -c "cd \"$start\" && vifm --select \"\$(fzf -e --preview='cat {}')\""
#else
  #echo "Invalid directory or no directory selected"
#fi


# Prompt for input
input=$(echo -e "ww\nhome\n" | dmenu -p "en qué dir empezar:")

# Map input to directories
case $input in
    "ww")
        start="/home/ttdduu/wiki"
        ;;
    "home")
        start="/home/ttdduu"
        ;;
    "/")
        start="//"
        ;;
esac

# Check if ignoring dotfiles is selected
#if [ "$start" == ".ignore dotfiles" ]; then
    #input=$(ls -d /home/ttdduu/* | dmenu -p "Select a directory (ignoring dotfiles):")
    #if [[ $input =~ ^/home/ttdduu/\. ]]; then
        #start=""
    #else
        #start=$input
    #fi
#fi

# Validate and execute the rest of the script
if [[ -n "$start" && -d "$start" ]]; then
    st -e zsh -c "cd \"$start\" && vifm --select \"\$(fzf -e --preview='cat {}')\""
else
    echo "Invalid directory or no directory selected"
fi
