#!/usr/bin/zsh

#cd "$(dirname "$(find ./ -name "$1" -print -quit)")"
#st -e vifm --select $(fzf -e)
#st -e fzf | vifm --select &
#st -e fzf | xargs -I {} vifm --select {}

st -e zsh -c 'cd // && vifm --select "$(fzf -e)"' &

