#!/bin/zsh

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1003/bus

pen_id=$( xsetwacom list devices | cut -d : -f 2 | cut -d ' ' -f 2 | cut -c 1-2 | cut -d ' ' -f 2 | cut -d$'\n' -f 1
)
eraser_id=$( xsetwacom list devices | cut -d : -f 2 | cut -d ' ' -f 2 | cut -c 1-2 | cut -d ' ' -f 2 | cut -d$'\n' -f 2
)


if [[ $(xrandr -q | grep 'HDMI1 connected 1920') ]]; then

	xsetwacom set $pen_id MapToOutput 1920x1296+0+0
	xsetwacom set $eraser_id MapToOutput 1920x1296+0+0
fi

if [ $# -eq 0 ]; then
	cp $HOME/TEMPLATE_XOURNALPIPI_DEJALO_INTACTO.xopp $HOME/newxopp.xopp
	xournalpp $HOME/newxopp.xopp
else
	xournalpp $1
fi
